project_id = "minypmsdvdhktkekbeaj"

[functions.propiedades]
verify_jwt = false

[functions.ubicaciones]
verify_jwt = false

[functions.upload-image]
verify_jwt = false

[functions.mercadolibre-comparables]
verify_jwt = false
